language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
 - composer install --prefer-source --dev
 - mkdir -p data/logs

script:
 - ./vendor/bin/phpunit --bootstrap=test/Bootstrap.php

notifications:
  email:
    - cyawman@gmail.com

